type Mutation {
    addQuestion(input: QuestionInput!): Question
    addAnswer(questionId: String!, text: String!): Answer
}

type Query {
    getQuestions(eventId: String!): [Question]
}

input QuestionInput {
    eventId: String!
    text: String!
}