type Mutation {
    createCategory(categoryName: String!): String
    editCategory(categoryId: String!, categoryName: String!): Boolean
    deleteCategory(categoryId: String!): Boolean
}

type Query {
    getCategories: [Category]
}
