type Mutation {
    createEvent(eventDetails: EventInput!): String
    joinEvent(eventId: String!): String
    leaveEvent(eventId: String!): String
}

type Query {
    getUserEvents(offset: Int): UserEventsResponse
    searchEvents(searchInput: String): [Event]
    getEvent(eventId: String!): Event
}

type UserEventsResponse {
    events: [Event]
    eventsNumber: Int
    hasMore: Boolean
}

input EventInput {
    location: LocationInput
    title: String!
    description: String!
    startDate: Date!
    endDate: Date
    categoriesId: [String]
    uploadPhoto: Upload
}

input LocationInput {
    latitude: String!
    longitude: String!
    addressName: String
}
