type Mutation {
    createEvent(eventDetails: EventInput!): String
    joinEvent(eventId: String!): String
    leaveEvent(eventId: String!): String
    getUserEvents: [Event]
}

input EventInput {
    location: LocationInput
    title: String!
    description: String!
    startDate: Date!
    endDate: Date
    categoriesId: [String]
    uploadPhoto: Upload
}

input LocationInput {
    latitude: String!
    longitude: String!
    addressName: String
}
