export * from './register'
export * from './main'
export * from './loading'
export * from './event'
export * from './edit'
export * from './reviews'
export * from './contact'
export * from './questions'
