const strings = {
  welcome: 'Welcome to RetrUp',
  chooseFeedComponent: 'Choose some of your interests',
  email: 'Email',
  password: 'Password',
  repeatPassword: 'Repeat password',
  forgotPassword: 'Forgot your password ?',
  login: 'Log in',
  or: 'or',
  facebookLogin: 'Continue with Facebook',
  notOnApp: 'Not on RetrUp yet? Sign up',
  signup: 'Sign up',
  providePassword: 'Please provide a password of at least 6 characters',
  passwordsDontMatch: 'The passwords provided don\'t match',
  enterDetailsDescription: 'Let us know you',
  skip: 'Skip',
  search: 'Search',
  whatToSearchFor: "Search for events nearby",
  searchPlaceholder: "Search for an event",
  firstName: 'First Name',
  lastName: 'Last Name',
  error: 'Something went wrong! Please try again',
  notifications: 'Notifications',
  home: 'Home',
  userprofile: "Profile",
  going: "Going events",
  created: "Created events",
  noNotifications: 'You don’t have any notifications yet. Start exploring the events!',
  noGoingEvents: 'You are not going to any event yet. Start exploring the events!',
  noCreatedEvents: 'You haven\'t created an event yet. When you\'ll have something to share, feel free to create an event!',
  save: 'Save',
  loadMore: 'Load more',
  noCameraAccess: 'We don\'t have access to your camera. Please go to setting and change the permissions in order to take photos'
}

export default strings
