type User {
  _id: ID!
  username: String
  email: String
  profile: UserStandardProfile
  emails: [UserEmail]
  roles: [String]
  phone: Phone
  ownedEvents: [Event]
  participatingEvents: [Event]
  news: [Notification]
  followingCategories: [Category]
}

type UserEmail {
  address: String
  verified: Boolean
}

type UserEmail {
  address: String
  verified: Boolean
}

type UserStandardProfile {
  firstName: String
  lastName: String
  fullName: String
  avatarId: String
  ##avatar: AppUpload
  phoneNumber: String
  dateOfBirth: Date
  gender: GenderEnum
  categoryIds: [String]
}

type Phone {
  number: String,
  verified: Boolean
}

enum RolesEnum {
  ADMIN
  ORGANISER
  USER
}

enum GenderEnum {
  MALE
  FEMALE
}
