type Mutation {
    registerMember(input: ProfileInput!): Boolean
    addMemberDetails(email: String!, details: DetailsInput!): Boolean
    addMemberCategories(email: String!, categories: [String]!): Boolean
    addPushToken(token: String!): Boolean
    loginMember(loginInput: LoginInput!): LoginResponse
}

type Query {
    getUserInfo(userId: String): User
}

input ProfileInput {
    email: String!
    password: String!
}

input DetailsInput {
    firstName: String
    lastName: String
}

type RegisterResponse {
    message: String
    success: Boolean
}

input LoginInput {
    email: String!
    password: String!
}

type LoginResponse {
    token: String!
    userId: String!
}
