type Mutation {
    registerMember(input: ProfileInput!): Boolean
    addMemberDetails(email: String!, details: DetailsInput!): Boolean
    addMemberCategories(categories: [String]!): Boolean
}

input ProfileInput {
    email: String!
    password: String!
}

input DetailsInput {
    firstName: String
    lastName: String
}

type RegisterResponse {
    message: String
    success: Boolean
}
