type Mutation {
    registerMember(input: ProfileInput!): AuthResponse
    addMemberDetails(email: String!, details: DetailsInput!): Boolean
    addMemberCategories(email: String!, categories: [String]!): Boolean
    addPushToken(token: String!): Boolean
    loginMember(loginInput: LoginInput!): AuthResponse
    updateUserInfo(userInfo: UserInfoInput!): Boolean
    setUserPassword(email: String!, newPassword: String!): Boolean
}

type Query {
    getUserInfo(userId: String): User
}

input UserInfoInput {
    firstName: String
    lastName: String
    email: String
    categoriesId: [String]
}

input ProfileInput {
    email: String!
    password: String!
}

input DetailsInput {
    firstName: String
    lastName: String
}

type RegisterResponse {
    message: String
    success: Boolean
}

input LoginInput {
    email: String!
    password: String!
}

type AuthResponse {
    token: String!
    userId: String!
}
