type Mutation {
    addReview(input: ReviewInput!): Event
    editReview(reviewId: String!, input: EditReviewInput!): Event
    deleteReview(reviewId: String!): Boolean
}

type Query {
    getReviews(eventId: String!): [Review]
}

input EditReviewInput {
    stars: Int
    title: String!
    description: String!
}

input ReviewInput {
    eventId: String!
    stars: Int
    title: String!
    description: String!
}