type Mutation {
    registerUser(input: String): RegisterResponse
}

input ProfileInput {
    email: String!
    password: String!
    firstName: String
    lastName: String
}

type RegisterResponse {
    message: String
    success: Boolean
}
